# Generated by Django 3.0.8 on 2020-08-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandsweuse',
            options={'verbose_name_plural': 'Brands Used'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='galleryimages',
            options={'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='makeupservice',
            options={'verbose_name_plural': 'Makeup Services'},
        ),
        migrations.AlterModelOptions(
            name='makeupservicetype',
            options={'verbose_name_plural': 'Makeup Service Types'},
        ),
        migrations.RenameField(
            model_name='makeupservice',
            old_name='makeup_service_id',
            new_name='makeup_service',
        ),
    ]
