# Generated by Django 3.0.8 on 2020-08-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200802_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandsweuse',
            name='online_link',
        ),
        migrations.AddField(
            model_name='galleryimages',
            name='image_type',
            field=models.CharField(choices=[('bridal', 'Bridal'), ('party', 'Party'), ('reception', 'Reception')], default='bridal', max_length=15),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='online_link',
            field=models.BooleanField(default=True),
        ),
    ]
