# Generated by Django 2.2.1 on 2020-08-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200803_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeupoffers',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='makeupoffers',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
