# Generated by Django 2.2.1 on 2020-08-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200803_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeupoffers',
            name='direction',
            field=models.CharField(default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='makeupoffers',
            name='speed',
            field=models.IntegerField(default=10),
        ),
    ]
